_target_: src.models.image_module.ImageLightningModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: torchvision.models.VisionTransformer
  num_classes: null
  patch_size: 1 # must be a divisor of image_size
  num_layers: 4
  num_heads: 12
  hidden_dim: 192
  mlp_dim: 768
  image_size: 32

# compile model for faster training with pytorch 2.0
compile: false