_target_: src.models.binary_grid_module.BinaryGridLightningModule
# _target_: src.models.mc_classification_module.MultiClassClassificationLightningModule

net:
  _target_: src.models.components.toy_mlp_classification.ToyMLPClassification
  img_width: null
  img_height: null
  hidden_dim: null
  num_layers: null
  num_classes: null

optimizer: null
scheduler: null
# compile model for faster training with pytorch 2.0
compile: false
